# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingdaily',
            name='vol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tradingdaily',
            unique_together=set([('company', 'date')]),
        ),
    ]
