# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20171112_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingdaily',
            name='close',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradingdaily',
            name='high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradingdaily',
            name='low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradingdaily',
            name='open',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradingdaily',
            name='ref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
