# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_company_vn30'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingdaily',
            name='agreement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingdaily',
            name='foreign_buy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingdaily',
            name='foreign_sell',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
