# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20171116_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
