# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171120_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'DRAFT'), (2, 'PUBLISHED')], default=1),
        ),
    ]
